name: Build Flutter Windows

on:
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-windows:
    runs-on: windows-2022

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Flutter doctor
        run: flutter doctor -v

      - name: Enable Windows desktop
        run: flutter config --enable-windows-desktop

      - name: Create .env
        shell: pwsh
        run: |
          Set-Content -Path ".env" -Value "${{ secrets.ENV_FILE }}" -Encoding UTF8

      - name: Check .env exists
        shell: pwsh
        run: |
          Get-ChildItem -Force
          if (!(Test-Path ".env")) { exit 1 }
          Write-Host ".env found"

      - name: Get dependencies
        run: flutter pub get

      - name: Clean
        run: flutter clean

      - name: Build Windows release
        run: flutter build windows --release -v

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: flutter-windows-release
          path: build/windows/x64/runner/Release